[2025-04-03 16:13:59 +0800] [74354] [INFO] Starting gunicorn 23.0.0
[2025-04-03 16:13:59 +0800] [74354] [INFO] Listening at: https://0.0.0.0:8843 (74354)
[2025-04-03 16:13:59 +0800] [74354] [INFO] Using worker: uvicorn.workers.UvicornWorker
[2025-04-03 16:13:59 +0800] [74355] [INFO] Booting worker with pid: 74355
[2025-04-03 16:13:59 +0800] [74356] [INFO] Booting worker with pid: 74356
[2025-04-03 16:14:04 +0800] [74355] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/Users/zhangjun/PycharmProjects/crtool/.venv/lib/python3.10/site-packages/gunicorn/arbiter.py", line 608, in spawn_worker
    worker.init_process()
  File "/Users/zhangjun/PycharmProjects/crtool/.venv/lib/python3.10/site-packages/uvicorn/workers.py", line 75, in init_process
    super().init_process()
  File "/Users/zhangjun/PycharmProjects/crtool/.venv/lib/python3.10/site-packages/gunicorn/workers/base.py", line 135, in init_process
    self.load_wsgi()
  File "/Users/zhangjun/PycharmProjects/crtool/.venv/lib/python3.10/site-packages/gunicorn/workers/base.py", line 147, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/Users/zhangjun/PycharmProjects/crtool/.venv/lib/python3.10/site-packages/gunicorn/app/base.py", line 66, in wsgi
    self.callable = self.load()
  File "/Users/zhangjun/PycharmProjects/crtool/.venv/lib/python3.10/site-packages/gunicorn/app/wsgiapp.py", line 57, in load
    return self.load_wsgiapp()
  File "/Users/zhangjun/PycharmProjects/crtool/.venv/lib/python3.10/site-packages/gunicorn/app/wsgiapp.py", line 47, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/Users/zhangjun/PycharmProjects/crtool/.venv/lib/python3.10/site-packages/gunicorn/util.py", line 370, in import_app
    mod = importlib.import_module(module)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/Users/zhangjun/PycharmProjects/crtool/backend/main.py", line 70, in <module>
    app.mount("/static", StaticFiles(directory="apps/static"), name="static")
  File "/Users/zhangjun/PycharmProjects/crtool/.venv/lib/python3.10/site-packages/starlette/staticfiles.py", line 59, in __init__
    raise RuntimeError(f"Directory '{directory}' does not exist")
RuntimeError: Directory 'apps/static' does not exist
[2025-04-03 16:14:04 +0800] [74355] [INFO] Worker exiting (pid: 74355)
[2025-04-03 16:14:04 +0800] [74356] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/Users/zhangjun/PycharmProjects/crtool/.venv/lib/python3.10/site-packages/gunicorn/arbiter.py", line 608, in spawn_worker
    worker.init_process()
  File "/Users/zhangjun/PycharmProjects/crtool/.venv/lib/python3.10/site-packages/uvicorn/workers.py", line 75, in init_process
    super().init_process()
  File "/Users/zhangjun/PycharmProjects/crtool/.venv/lib/python3.10/site-packages/gunicorn/workers/base.py", line 135, in init_process
    self.load_wsgi()
  File "/Users/zhangjun/PycharmProjects/crtool/.venv/lib/python3.10/site-packages/gunicorn/workers/base.py", line 147, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/Users/zhangjun/PycharmProjects/crtool/.venv/lib/python3.10/site-packages/gunicorn/app/base.py", line 66, in wsgi
    self.callable = self.load()
  File "/Users/zhangjun/PycharmProjects/crtool/.venv/lib/python3.10/site-packages/gunicorn/app/wsgiapp.py", line 57, in load
    return self.load_wsgiapp()
  File "/Users/zhangjun/PycharmProjects/crtool/.venv/lib/python3.10/site-packages/gunicorn/app/wsgiapp.py", line 47, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/Users/zhangjun/PycharmProjects/crtool/.venv/lib/python3.10/site-packages/gunicorn/util.py", line 370, in import_app
    mod = importlib.import_module(module)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/Users/zhangjun/PycharmProjects/crtool/backend/main.py", line 70, in <module>
    app.mount("/static", StaticFiles(directory="apps/static"), name="static")
  File "/Users/zhangjun/PycharmProjects/crtool/.venv/lib/python3.10/site-packages/starlette/staticfiles.py", line 59, in __init__
    raise RuntimeError(f"Directory '{directory}' does not exist")
RuntimeError: Directory 'apps/static' does not exist
[2025-04-03 16:14:04 +0800] [74356] [INFO] Worker exiting (pid: 74356)
[2025-04-03 16:14:05 +0800] [74354] [ERROR] Worker (pid:74355) exited with code 3
[2025-04-03 16:14:05 +0800] [74354] [ERROR] Worker (pid:74356) was sent SIGTERM!
[2025-04-03 16:14:05 +0800] [74354] [ERROR] Shutting down: Master
[2025-04-03 16:14:05 +0800] [74354] [ERROR] Reason: Worker failed to boot.
[2025-04-03 16:36:42 +0800] [75000] [INFO] Starting gunicorn 23.0.0
[2025-04-03 16:36:42 +0800] [75000] [INFO] Listening at: https://0.0.0.0:8843 (75000)
[2025-04-03 16:36:42 +0800] [75000] [INFO] Using worker: uvicorn.workers.UvicornWorker
[2025-04-03 16:36:42 +0800] [75001] [INFO] Booting worker with pid: 75001
[2025-04-03 16:36:42 +0800] [75002] [INFO] Booting worker with pid: 75002
[2025-04-03 16:36:47 +0800] [75002] [INFO] Started server process [75002]
[2025-04-03 16:36:47 +0800] [75001] [INFO] Started server process [75001]
[2025-04-03 16:36:47 +0800] [75002] [INFO] Waiting for application startup.
[2025-04-03 16:36:47 +0800] [75001] [INFO] Waiting for application startup.
[2025-04-03 16:36:49 +0800] [75002] [INFO] Application startup complete.
[2025-04-03 16:36:49 +0800] [75001] [INFO] Application startup complete.
[2025-04-03 16:37:38 +0800] [75000] [INFO] Handling signal: int
[2025-04-03 16:37:38 +0800] [75001] [INFO] Shutting down
[2025-04-03 16:37:38 +0800] [75001] [INFO] Error while closing socket [Errno 9] Bad file descriptor
[2025-04-03 16:37:38 +0800] [75002] [INFO] Shutting down
[2025-04-03 16:37:38 +0800] [75002] [INFO] Error while closing socket [Errno 9] Bad file descriptor
[2025-04-03 16:37:38 +0800] [75001] [INFO] Waiting for connections to close. (CTRL+C to force quit)
[2025-04-03 16:37:38 +0800] [75002] [INFO] Waiting for application shutdown.
[2025-04-03 16:37:38 +0800] [75002] [INFO] Application shutdown complete.
[2025-04-03 16:37:38 +0800] [75002] [INFO] Finished server process [75002]
[2025-04-03 16:37:38 +0800] [75000] [ERROR] Worker (pid:75002) was sent SIGINT!
[2025-04-03 16:37:38 +0800] [75001] [INFO] Finished server process [75001]
[2025-04-03 16:37:38 +0800] [75000] [ERROR] Worker (pid:75001) was sent SIGINT!
[2025-04-03 16:37:38 +0800] [75000] [INFO] Shutting down: Master
